#! /bin/bash

ncpus=$1
version="15.0.0" #indicates the version of llvm you are building

cd /;
wget https://github.com/llvm/llvm-project/archive/refs/heads/main.zip -O /llvm-project.zip;
unzip /llvm-project.zip;

mkdir /llvm_build;
cd /llvm_build;
cmake -G "Unix Makefiles" \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/usr/local/llvm \
      -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" \
      /llvm-project-main/llvm

cd tools/clang/tools/extra/clang-tidy;
make -j${ncpus} install;

mkdir /build_output;
cd /usr/local/;
mkdir -p "llvm/lib64/clang/$version/include"
cp -r /llvm-project-main/clang/lib/Headers/. "llvm/lib64/clang/$version/include"
tar -czf "/build_output/clang-tidy-$version-x86_64-linux-rhel-8.1.tar.xz" llvm;