#! /bin/bash

ncpus=2

help="
Usage

    $(basename $0) [OPTIONS]

Options

    -h            = see help
    -j <ncpus>    = assign <ncpus> logical cores for the container to use
"

while getopts "j:h" opt
do
    case $opt in
        h) echo "$help"; exit;;
        j) ncpus=$OPTARG;;
        \?) echo "$help"; exit;;
    esac
done

echo "Launching build server container with $ncpus logical cores "
docker build --build-arg ncpus=$ncpus -t build_server .
docker run -it --cpus="$ncpus" -v "$(pwd):/build_output_host" build_server cp -r /build_output/. /build_output_host