#!/bin/bash

export PYTHONIOENCODING="UTF-8"

echo "Compiling ..."

mkdir -p bin

compile_result=$(bash scripts/compile.sh)

# Check if output generated by calling compile
# contains the keyword success, continue if so.
if [[ $compile_result =~ "success" ]]
then
  echo "Compilation successful"
  echo "Running ..."
  bin/a.out
else
  echo "Compilation failed"
fi
