#! /bin/bash

# run this in the numcse_monolith image
# https://stackoverflow.com/questions/47255526/how-to-build-the-latest-clang-tidy
# https://github.com/llvm/llvm-project/releases/tag/llvmorg-13.0.1
# https://clang.llvm.org/docs/LibTooling.html#libtooling-builtin-includes
# todo: clang-tidy requires its lib64 files, provide those in the pre-built binaries
# sparse checkout is more difficult now for llvm 14: https://github.com/llvm/llvm-project/issues/53281, maybe
# use a compute node and build there


ncpus=$0
version="13.0.1"

wget "https://github.com/llvm/llvm-project/releases/download/llvmorg-$version/llvm-$version.src.tar.xz" \
      && mkdir /llvm \
      && tar -xf "llvm-$version.src.tar.xz" -C llvm --strip-components 1 \
      && cd /llvm/tools \
      && wget "https://github.com/llvm/llvm-project/releases/download/llvmorg-$version/clang-$version.src.tar.xz" \
      && mkdir clang \
      && tar -xf "clang-$version.src.tar.xz" -C clang --strip-components 1 \
      && cd clang/tools \
      && wget "https://github.com/llvm/llvm-project/releases/download/llvmorg-$version/clang-tools-extra-$version.src.tar.xz" \
      && mkdir extra \
      && tar -xf "clang-tools-extra-$version.src.tar.xz" -C extra --strip-components 1;

mkdir /llvm_build \
      && cd /llvm_build \
      && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/llvm -DCLANG_BUILD_TOOLS=ON ../llvm \
      && cd tools/clang/tools/extra/clang-tidy \
      && make -j${ncpus} install;

cd /usr/local/ \
      && tar -czf "/numcse/CodeExpertTool/bin/clang-tidy-$version-x86_64-linux-rhel-8.1.tar.xz" llvm;